services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data

  web:
    image: node:lts
    user: 'node'
    env_file: .env
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm run testandrun'
